version: "3"

services:

  varnish:
#    image: wodby/drupal-varnish:4.1
    image: nbcwebcontainers.azurecr.io/appservice-drupal-varnish:4.1
    environment:
#      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: localhost
      VARNISH_BACKEND_PORT: 8080
      STUNNEL_BACKEND_HOST: nbcweb-drupal-01.azurewebsites.net
      STUNNEL_BACKEND_PORT: 443
    ports:
      - "6081:6081"
      - "2222:2222"
